apiVersion: v2
name: helm-wordpress
description: A Helm chart for Wordpress
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  ### Wordpress ###
  - name: wordpress
    version: "16.1.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: wordpress.enabled

  - name: mysql
    version: "9.10.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
