### Wordpress ###
wordpress:
  enabled: true
  replicaCount: 1
  wordpressScheme: https
  wordpressUsername: admin
  existingSecret: 'wordpress-user-login'
  
  image:
    tag: 5.7.9 #6.3.0
  
  readinessProbe:
    enabled: false

  ingress:
    enabled: false

  service:
    type: ClusterIP

  mariadb:
    enabled: false

  externalDatabase:
    port: 3306
    database: wordpress
    user: root
    existingSecret: wordpress-db-login

mysql:
  enabled: true
  auth:
    database: wordpress
    existingSecret: wordpress-db-login
