apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ing-3
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true" #Wordpress will redirect to https internally
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://{{ .Values.domainWordpress3 }}/epeagle;
spec:
  tls:
    - hosts:
      - {{ .Values.domainWordpress3 }}
      - www.{{ .Values.domainWordpress3 }}
      secretName: wordpress-cert-3
  rules:
    - host: {{ .Values.domainWordpress3 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-{{ .Values.envAlias }}
                port:
                  number: 443
  
    - host: www.{{ .Values.domainWordpress3 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-{{ .Values.envAlias }}
                port:
                  number: 443
