apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
spec:
  secretName: wordpress-cert
  dnsNames:
    - {{ .Values.domainWordpress }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
