apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-user-login
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: wordpress-user-login       # name of the k8s Secret to be created
  data:
  - secretKey: "wordpress-password" # For MariaDB
    remoteRef:
      key: initial-secret
      property: WORDPRESS_PASSWORD # Use the same as Magento
