apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert-2
spec:
  secretName: wordpress-cert-2
  dnsNames:
    - {{ .Values.domainWordpress2 }}
    - www.{{ .Values.domainWordpress2 }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
